language: java
jdk:
- openjdk8

sudo: false
install: true

branches:
  only:
   - lab1


script:
  - ./webapp/gradlew build
  - cd webapp
  - gradlew war


notifications:
  username:
    recipients:
      - zhang.yichu@husky.neu.edu
