language: java
jdk:
- openjdk8

sudo: false
install: true

branches:
  only:
   - lab1


script:
  - cd webapp
  - ./gradlew war

after_success:
  - mkdir codedeploy
  - zip -r csye6225-lab-$TRAVIS_JOB_NUMBER.zip build/libs/ROOT.war infrastructure/aws/codedeploy/appspec.yml
  - ls -al
  - mv csye6225-lab-$TRAVIS_JOB_NUMBER.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd
  - cd ..
  - pwd
  
notifications:
  username:
    recipients:
      - zhang.yichu@husky.neu.edu
